### ISSUE TITLE
Serious performance issues

### ISSUE THREAD

**Issue by EbrahimMalek** [leorohr/simulus#43]
The performance issues caused by a large number of vehicles on the map currently brings 2 main concerns to the forefront:
1. Framerate slows down considerably, interfering with the "tickrate" slider change mechanism. 
2. Vehicles appear to slow down collectively for no apparent reason. 

The solutions I propose to tackle these problems:

-> Currently, a vehicle that moves off screen is removed from the canvas, but technically still exists in the arraylist of vehicles. This means that the GUI continues to pass information to that vehicle and run its methods even after the vehicle is offscreen. Removing the vehicle from the arraylist of vehicles on the fly will ofcourse cause a concurrent modification exception that needs to be handled.

-> Limit the tile size considerably. Keep the maps relatively large scale, 2-4 junctions at most on a single map. I feel that our map editing functionality will make up for where our simulation lacks in scalability. 

Finally, I would like to challenge the notion that we MUST use a discrete time approach. It is not only reducing the fluidity of our simulation but is inhibiting our ability to animate. The more continuous our approach becomes in terms of both space and time, the more closely we simulate an instance of the real world. The real world is simply not discrete, and our simulation has been developed using real world logic so far.

**Comment by leorohr** [comment]
Removing the cars from the according lists should indeed speed-up the simulation. 
I do agree that we do not have to use a discrete time approach. However, the way I see it, using the animation timer the way we do now, does also not yield a continuous time approach, because the simulation is executed all at once in each execution of the handle method - i.e. with each execution all the cars move. This is, imo, a discrete time approach with the caveat that the time steps are not fixed but depend on the execution time of the handle method.
A discrete time model can still yield fluent animations, as a ticketrate of say 15ms will yield 66fps.
